# Generated by Django 2.0.8 on 2018-09-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpagegalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagegalleryimage',
            old_name='imgae',
            new_name='image',
        ),
    ]
